services:
  postgres: #name of the service
    container_name: postgres_nftauction_container #container name
    image: postgres #repository image name
    environment:
      #- POSTGRES_USER=PostgresBarisUser we use default user name, in appsettings json
      - POSTGRES_PASSWORD=postgresbarispassword
      #- POSTGRES_DB=PostgresNFTAuctions no need to define here second time for now
    ports:
      # access Postgress Inside/Outside of Docker on that ports
      - 5432:5432
    volumes:
      #this allows Docker to use external storage to Docker, our operating system storage to store the data for our database.
      - nftauctionpostgre:/var/lib/postgresql/data
  mongodb:
    container_name: mongo_nftauction_container
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongobarispassword
    ports:
      - 27017:27017
    volumes:
      - nftauctionmongodata:/var/lib/mongodb/data
  rabbitmq: #default username and password: guest
    container_name: rabbitmq_nftauction_container
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
volumes:
  nftauctionpostgre:
  nftauctionmongodata: