import type { Metadata } from 'next'
import './globals.css'
import Navbar from './nav/Navbar'


export const metadata: Metadata = {
  title: 'NFT Market Place',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar/>
        <main className=' container mx-auto px-7 pt-7'>
          {children}
        </main>
      </body>
    </html>
  )
}
